### ISSUE TITLE
Dawn theme has unreadable help page

### ISSUE THREAD

**Issue by mvllow** [rose-pine/amfora#1]
1. Open amfora
2. Press `?` for help
3. Text is unreadable

Dark variants are working fine - couldn't find any text variables being set to a light colour hmm

**Comment by sam51210** [comment]
c o n f u s e d

**Comment by mvllow** [comment]
**Starting amfora with dawn theme**

<img width="540" alt="Screen Shot 2021-08-06 at 09 19 15" src="https://user-images.githubusercontent.com/1474821/128524454-fc90488d-d4c6-43ba-a1b5-e570ea859bd6.png">

**After pressing `?`**

<img width="540" alt="Screen Shot 2021-08-06 at 09 19 28" src="https://user-images.githubusercontent.com/1474821/128524463-354dea2c-c01c-4f3e-9de2-5a5e7767a9ec.png">

**Comment by mvllow** [comment]
This seems to have been fixed upstream 😌
